<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <Company>Extreme Solutions</Company>
	  <Product>CAMT053 Parser</Product>
	  <Copyright>Copyright - Extreme Solutions - 2026 - All rights reserved</Copyright>
      <VersionDate>$([System.DateTime]::UtcNow.ToString('yyMM'))</VersionDate>
      <BuildNumber>$([System.Int32]::Parse($([System.DateTime]::Now.Subtract($([System.DateTime]::Parse($([System.DateTime]::Now.ToString('yyyy-MM-01'))))).TotalMinutes.ToString('F0'))))</BuildNumber>
      <Version>$(VersionDate)</Version>
      <AssemblyVersion>1.1.$(VersionDate).$(BuildNumber)</AssemblyVersion>
      <FileVersion>1.1.$(VersionDate).$(BuildNumber)</FileVersion>
	  <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	  <Title>Extreme Solutions CAMT053 Parser library</Title>
	  <PackageLicenseExpression>MIT</PackageLicenseExpression>
	  <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
	  <PackageReadmeFile>README.md</PackageReadmeFile>
	  <ApplicationIcon>esParser.ico</ApplicationIcon>
	  <PackageIcon>esParser.png</PackageIcon>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <ShouldCreateLogs>True</ShouldCreateLogs>
    <AdvancedSettingsExpanded>False</AdvancedSettingsExpanded>
    <UpdateAssemblyVersion>False</UpdateAssemblyVersion>
    <UpdateAssemblyFileVersion>False</UpdateAssemblyFileVersion>
    <UpdateAssemblyInfoVersion>False</UpdateAssemblyInfoVersion>
    <UpdatePackageVersion>False</UpdatePackageVersion>
    <AssemblyInfoVersionType>SettingsVersion</AssemblyInfoVersionType>
    <InheritWinAppVersionFrom>None</InheritWinAppVersionFrom>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="esParser.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="esParser.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
